//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbSport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities
    {
        public System.Guid Id { get; set; }
        public System.Guid ExerciseId { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public int DurationMinutes { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> CaloriesBurned { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Exercises Exercises { get; set; }
    }
}
