USE Sport;
GO

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(200) NOT NULL,
    RegisteredAt DATETIME NOT NULL DEFAULT GETDATE(),
    IsActive BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE Programs (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Programs_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

CREATE TABLE Exercises (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ProgramId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Exercises_Programs FOREIGN KEY (ProgramId) REFERENCES Programs(Id)
);
GO

CREATE TABLE Activities (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ExerciseId UNIQUEIDENTIFIER NOT NULL,
    ActivityDate DATE NOT NULL,
    DurationMinutes INT NOT NULL,
    Notes NVARCHAR(200) NULL,
    CaloriesBurned DECIMAL(6,2) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Activities_Exercises FOREIGN KEY (ExerciseId) REFERENCES Exercises(Id)
);
GO

CREATE TABLE MuscleGroups (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(50) NOT NULL
);
GO

CREATE TABLE ExerciseMuscleGroups (
    ExerciseId UNIQUEIDENTIFIER NOT NULL,
    MuscleGroupId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT PK_ExerciseMuscleGroups PRIMARY KEY (ExerciseId, MuscleGroupId),
    CONSTRAINT FK_EMG_Exercises FOREIGN KEY (ExerciseId) REFERENCES Exercises(Id),
    CONSTRAINT FK_EMG_MuscleGroups FOREIGN KEY (MuscleGroupId) REFERENCES MuscleGroups(Id)
);
GO